dist: focal
language: java
jdk:
  - openjdk11
before_install:
  - pwd
  - wget https://services.gradle.org/distributions/gradle-6.5-bin.zip
  - unzip gradle-6.5-bin.zip
  - export PATH=gradle-6.5/bin:$PATH
  - gradle -version
  - cat /etc/issue
  - which java
  - java -version
script:
  - gradle clean build test
  - gradle --build-file di-examples/build.gradle clean test
